name: 'dbt_training'
config-version: 2
version: '1.0.0'

profile: 'dbt_training_dw'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets: [target, dbt_packages]

models:
  dbt_training:
    materialized_dwh:
      +materialized: table
