version: 2

models:
  - name: employee_names
    description: '{{ doc("table_employee_names") }}'
    columns:
      - name: employee_id
        tests:
        - unique
        - not_null
        - accepted_values:
            values: ['101', '102', '103']
        - is_not_negative
